---
swagger: "2.0"
info:
  description: "Environmental Exposures API"
  version: "1.0.0"
  title: "Environmental Exposures API"
  contact:
    name: "Michael J. Stealey"
    url: "http://renci.org"
    email: "stealey@renci.org"
host: "localhost:8080"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /exposures:
    get:
      tags:
      - "default"
      summary: "Get list of exposure types"
      description: "Returns a list of all available exposure types"
      operationId: "controllers.default_controller.exposures_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Exposure types"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/exposure_type"
        404:
          description: "No exposure types found"
  /exposures/{exposure_type}/values:
    get:
      tags:
      - "default"
      summary: "Get exposure value for a given environmental factor at exposure location(s)"
      description: "Retrieve the computed exposure value(s) for a given environmental\
        \ exposure factor, time period, and location(s)"
      operationId: "controllers.default_controller.exposures_exposure_type_values_get"
      produces:
      - "application/json"
      parameters:
      - name: "exposure_type"
        in: "path"
        description: "The name of the exposure factor (currently limited to pm25,\
          \ o3)."
        required: true
        type: "string"
        default: "pm25"
      - name: "start_date"
        in: "query"
        description: "The starting date to obtain exposures for (example 1985-04-12\
          \ is April 12th 1985). Currently time of day is ignored."
        required: true
        type: "string"
        default: "2010-01-01"
        format: "date"
      - name: "end_date"
        in: "query"
        description: "The ending date to obtain exposures for (example 1985-04-13\
          \ is April 13th 1985). Currently time of day is ignored."
        required: true
        type: "string"
        default: "2010-01-05"
        format: "date"
      - name: "exposure_point"
        in: "query"
        description: "A description of the location(s) to retrieve the exposure for.\
          \ Locaton may be a single geocoordinate (example '35.720278,-79.176389')\
          \ or a semicomma separated list of geocoord:dayhours giving the start and\
          \ ending hours on specific days of the week at that location (example '35.720278,-79.176389,Sa0813;35.720278,-79.176389,other')\
          \ indicates Saturdays from 8am to 1pm is at one location and all other times\
          \ are at another location. Hours should be in 24 hours time using 2 digits,\
          \ days of the week should be the first two characters of the day.If the\
          \ day of the week does not appear then the time periods apply to all days\
          \ (example '35.720278,-79.176389,0614,35.731944,-78.852778,1424') gives\
          \ two time periods for all days. If hours do not appear then the time period\
          \ applies to all hours of the day (example '35.720278,-79.176389,Sa,35.731944,-78.852778,Su')."
        required: true
        type: "string"
        default: "35.9131996,-79.0558445"
      - name: "temporal_resolution"
        in: "query"
        description: "The temporal resolution to use for results, should be one of\
          \ 'hour' or 'day'. Default is 'day'"
        required: false
        type: "string"
        default: "day"
      - name: "statistical_type"
        in: "query"
        description: "The statistic to use for results, should be one of 'max', 'mean',\
          \ or 'median'. Default is 'max'"
        required: false
        type: "string"
        default: "max"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/exposure"
        400:
          description: "Invalid exposure parameter"
        404:
          description: "Values not found for exposure type"
  /exposures/{exposure_type}/scores:
    get:
      tags:
      - "default"
      summary: "Get exposure score for a given environmental factor at exposure location(s)"
      description: "Retrieve the computed exposure score(s) for a given environmental\
        \ exposure factor, time period, and location(s)"
      operationId: "controllers.default_controller.exposures_exposure_type_scores_get"
      produces:
      - "application/json"
      parameters:
      - name: "exposure_type"
        in: "path"
        description: "The name of the exposure factor (currently limited to pm25,\
          \ o3)."
        required: true
        type: "string"
        default: "pm25"
      - name: "start_date"
        in: "query"
        description: "The starting date to obtain exposures for (example 1985-04-12\
          \ is April 12th 1985). Currently time of day is ignored."
        required: true
        type: "string"
        default: "2010-01-01"
        format: "date"
      - name: "end_date"
        in: "query"
        description: "The ending date to obtain exposures for (example 1985-04-13\
          \ is April 13th 1985). Currently time of day is ignored."
        required: true
        type: "string"
        default: "2010-01-05"
        format: "date"
      - name: "exposure_point"
        in: "query"
        description: "A description of the location(s) to retrieve the exposure for.\
          \ Locaton may be a single geocoordinate (example '35.720278,-79.176389')\
          \ or a semicomma separated list of geocoord:dayhours giving the start and\
          \ ending hours on specific days of the week at that location (example '35.720278,-79.176389,Sa0813;35.720278,-79.176389,other')\
          \ indicates Saturdays from 8am to 1pm is at one location and all other times\
          \ are at another location. Hours should be in 24 hours time using 2 digits,\
          \ days of the week should be the first two characters of the day.If the\
          \ day of the week does not appear then the time periods apply to all days\
          \ (example '35.720278,-79.176389,0614,35.731944,-78.852778,1424') gives\
          \ two time periods for all days. If hours do not appear then the time period\
          \ applies to all hours of the day (example '35.720278,-79.176389,Sa,35.731944,-78.852778,Su')."
        required: true
        type: "string"
        default: "35.9131996,-79.0558445"
      - name: "temporal_resolution"
        in: "query"
        description: "The temporal resolution to use for results, should be one of\
          \ 'hour' or 'day'. Default is 'day'"
        required: false
        type: "string"
        default: "day"
      - name: "score_type"
        in: "query"
        description: "The exposure score type to return. The accepted values vary\
          \ by exposure factor. For pm25 values are '7dayrisk', '14dayrisk' (NOT COMPLETE)"
        required: false
        type: "string"
        default: "7dayrisk"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/exposure"
        400:
          description: "Invalid exposure parameters"
        404:
          description: "Scores not found for exposure type"
  /exposures/{exposure_type}/coordinates:
    get:
      tags:
      - "default"
      summary: "Get exposure location(s) as latitude, longitude coordinates"
      description: "Returns paginated list of available latitude, longitude coordinates\
        \ for given exposure_type. Optionally the user can provide a latitude, longitude\
        \ coordinate with a radius in meters to discover if an exposure location is\
        \ within the requested range"
      operationId: "controllers.default_controller.exposures_exposure_type_coordinates_get"
      produces:
      - "application/json"
      parameters:
      - name: "exposure_type"
        in: "path"
        description: "The name of the exposure factor (currently limited to pm25,\
          \ o3)."
        required: true
        type: "string"
        default: "pm25"
      - name: "latitude"
        in: "query"
        description: "Search coordinates that match or are like 'latitude'"
        required: false
        type: "string"
      - name: "longitude"
        in: "query"
        description: "Search coordinates that match or are like 'longitude'"
        required: false
        type: "string"
      - name: "radius"
        in: "query"
        description: "radius in meters to search within for exposure point when a\
          \ coordinate is provided"
        required: false
        type: "string"
        default: "0"
      responses:
        200:
          description: "Exposure points"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/coordinate"
        404:
          description: "No coordinates found for exposure type"
  /exposures/{exposure_type}/dates:
    get:
      tags:
      - "default"
      summary: "Get exposure start date and end date range for exposure type"
      description: "Returns exposure start date and end date range for given exposure\
        \ type"
      operationId: "controllers.default_controller.exposures_exposure_type_dates_get"
      produces:
      - "application/json"
      parameters:
      - name: "exposure_type"
        in: "path"
        description: "The name of the exposure factor (currently limited to pm25,\
          \ o3)."
        required: true
        type: "string"
        default: "pm25"
      responses:
        200:
          description: "Date range"
          schema:
            $ref: "#/definitions/date_range"
        404:
          description: "No date range found for exposure type"
definitions:
  exposure:
    type: "object"
    required:
    - "exposure_type"
    properties:
      exposure_type:
        type: "string"
      start_time:
        type: "string"
        format: "date-time"
      end_time:
        type: "string"
        format: "date-time"
      value:
        type: "string"
      units:
        type: "string"
      latitude:
        type: "string"
        format: "float"
      longitude:
        type: "string"
        format: "float"
  exposure_type:
    type: "object"
    properties:
      exposure_type:
        type: "string"
      description:
        type: "string"
      units:
        type: "string"
      has_values:
        type: "boolean"
      has_scores:
        type: "boolean"
      schema_version:
        type: "string"
  coordinate:
    type: "object"
    properties:
      latitude:
        type: "string"
        format: "float"
      longitude:
        type: "string"
        format: "float"
  date_range:
    type: "object"
    properties:
      start_date:
        type: "string"
        format: "date-time"
      end_date:
        type: "string"
        format: "date-time"
parameters:
  exposure_type:
    name: "exposure_type"
    in: "path"
    description: "The name of the exposure factor (currently limited to pm25, o3)."
    required: true
    type: "string"
    default: "pm25"
  start_date:
    name: "start_date"
    in: "query"
    description: "The starting date to obtain exposures for (example 1985-04-12 is\
      \ April 12th 1985). Currently time of day is ignored."
    required: true
    type: "string"
    default: "2010-01-01"
    format: "date"
  end_date:
    name: "end_date"
    in: "query"
    description: "The ending date to obtain exposures for (example 1985-04-13 is April\
      \ 13th 1985). Currently time of day is ignored."
    required: true
    type: "string"
    default: "2010-01-05"
    format: "date"
  temporal_resolution:
    name: "temporal_resolution"
    in: "query"
    description: "The temporal resolution to use for results, should be one of 'hour'\
      \ or 'day'. Default is 'day'"
    required: false
    type: "string"
    default: "day"
  score_type:
    name: "score_type"
    in: "query"
    description: "The exposure score type to return. The accepted values vary by exposure\
      \ factor. For pm25 values are '7dayrisk', '14dayrisk' (NOT COMPLETE)"
    required: false
    type: "string"
    default: "7dayrisk"
  statistical_type:
    name: "statistical_type"
    in: "query"
    description: "The statistic to use for results, should be one of 'max', 'mean',\
      \ or 'median'. Default is 'max'"
    required: false
    type: "string"
    default: "max"
  exposure_point:
    name: "exposure_point"
    in: "query"
    description: "A description of the location(s) to retrieve the exposure for. Locaton\
      \ may be a single geocoordinate (example '35.720278,-79.176389') or a semicomma\
      \ separated list of geocoord:dayhours giving the start and ending hours on specific\
      \ days of the week at that location (example '35.720278,-79.176389,Sa0813;35.720278,-79.176389,other')\
      \ indicates Saturdays from 8am to 1pm is at one location and all other times\
      \ are at another location. Hours should be in 24 hours time using 2 digits,\
      \ days of the week should be the first two characters of the day.If the day\
      \ of the week does not appear then the time periods apply to all days (example\
      \ '35.720278,-79.176389,0614,35.731944,-78.852778,1424') gives two time periods\
      \ for all days. If hours do not appear then the time period applies to all hours\
      \ of the day (example '35.720278,-79.176389,Sa,35.731944,-78.852778,Su')."
    required: true
    type: "string"
    default: "35.9131996,-79.0558445"
  latitude:
    name: "latitude"
    in: "query"
    description: "Search coordinates that match or are like 'latitude'"
    required: false
    type: "string"
  longitude:
    name: "longitude"
    in: "query"
    description: "Search coordinates that match or are like 'longitude'"
    required: false
    type: "string"
  radius:
    name: "radius"
    in: "query"
    description: "radius in meters to search within for exposure point when a coordinate\
      \ is provided"
    required: false
    type: "string"
    default: "0"
