# Data Translator Environmental Exposure API
#
# This API provides access to environmental exposures. An exposure is
# any factor outside a human body that can act upon the body to cause
# a health impact, including chemical entities, biological entities,
# physical factors (e.g., sunlight, temperature), and social environmental 
# factors (e.g., crime-induced stress, poverty). 
#
# Exposures are parameterized by a range of temporal and spatial
#  factors that determine where a human has been and thus what factors they
#  were exposured to.
#
# Exposures are typically quantified at several levels:
#   - raw value: a measured quantity for the exposure factor typically taken
#       from an environmental sensor or other primary data collection method.
#   - exposure value: a quantity derived from raw values that computes a 
#       a net exposure to the factor for a range of spatial and temporal 
#       coordinates. This value is often the result of interpolating raw values
#       to cover all relevant spatial temporal coordinates. Values may also
#       combine different raw value sources, such as primary and secondary 
#       measures of air particulates. Requests for exposure values may
#       require indicating the computational method and parameters. 
#   - exposure score: a quantity derived from exposure and/or raw values that
#       relates the exposure value to a risk score for a particular disease. Thus
#       an exposure score for asthma may be different than a score for alzheimers
#       despite being based on the same exposure values.


swagger: '2.0'
info:
  version: 'v1'
  title: 'Environmental Exposures API'
  description: 'Environmental Exposures API'

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /mjstealey/environmental/v1
schemes:
 - https
 - http

paths:
  /exposures:
    get:
      summary: Get list of exposure types
      description: Returns a list of all available exposure types
      responses:
        200:
          description: Exposure types
          schema:
            type: array
            items:
              $ref: '#/definitions/exposure_type'
        404:
          description: No exposure types found
          
  /exposures/{exposure_type}/values:
    parameters:
      - $ref: '#/parameters/exposure_type'
    get:
      summary: Get exposure value for a given environmental factor
      description: "Retrieve the computed exposure value for a given environmental exposure factor, time period, and set of locations"
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/start_time'
        - $ref: '#/parameters/end_time'
        - $ref: '#/parameters/location'
        - $ref: '#/parameters/temporal_resolution'
        - $ref: '#/parameters/statistical_type'
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/exposures'
        400:
          description: Invalid exposure parameters
        404:
          description: Values not found for exposure type
          
  /exposures/{exposure_type}/scores:
    parameters:
      - $ref: '#/parameters/exposure_type'
    get:
      summary: Get exposure score for a given environmental factor
      description: "Retrieve the computed exposure score for a given environmental exposure factor, time period, and set of locations"
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/start_time'
        - $ref: '#/parameters/end_time'
        - $ref: '#/parameters/location'
        - $ref: '#/parameters/temporal_resolution'
        - $ref: '#/parameters/score_type'
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/exposures'
        400:
          description: Invalid exposure parameters
        404:
          description: Scores not found for exposure type
    
    

definitions:
  exposure_type:
    type: string
    
  exposure:
    required:
      - exposure_type
    properties:
      exposure_type:
        $ref: '#/definitions/exposure_type'
      start_time:
        type: string
        format: date-time
      end_time:
        type: string
        format: date-time
      value:
        type: string
      units:
        type: string
      latitude:
        type: string
        format: double
      longitude:
        type: string
        format: double
        
  exposures:
    type: array
    items:
      $ref: '#/definitions/exposure'
      
  exposure_location:
    required:
      - latitude
      - longitude
    properties:
      latitude:
        type: string
        format: double
      longitude:
        type: string
        format: double
      duration_start:
        type: string
        default: '00'
      duration_stop:
        type: string
        default: '23'
      duration_text:
        type: string
        default: 'other'


parameters:
  exposure_type:
    name: exposure_type
    in: path
    required: true
    description: "The name of the exposure factor (currently limited to pm25, ozone)."
    type: string
    
  start_time:
    name: start_time
    in: query
    required: true
    description: "The starting date to obtain exposures for (example 1985-04-12 is April 12th 1985). Currently time of day is ignored."
    type: string
    format: date
    
  end_time:
    name: end_time
    in: query
    required: true
    description: "The ending date to obtain exposures for (example 1985-04-13 is April 13th 1985). Currently time of day is ignored."
    type: string
    format: date
    
  temporal_resolution:
    name: temporal_resolution
    in: query
    required: false
    description: "The temporal resolution to use for results, should be one of 'hour' or 'day'. Default is 'day'"
    type: string
    default: 'day'
    
  score_type:
    name: score_type
    in: query
    required: false
    description: "The exposure score type to return. The accepted values vary by exposure factor. For pm25 values are '7dayrisk', '14dayrisk' (NOT COMPLETE)"
    type: string
    default: '7dayrisk'
    
  statistical_type:
    name: statistical_type
    in: query
    required: false
    description: "The statistic to use for results, should be one of 'max', 'mean', or 'median'. Default is 'max'"
    type: string
    default: 'max'
    
  location:
    name: location
    in: query
    required: true
    description: "A description of the location(s) to retrieve the exposure for. Locaton may be a single geocoordinate (example '35.720278,-79.176389') or a semicomma separated list of geocoord:dayhours giving the start and ending hours on specific days of the week at that location (example '35.720278,-79.176389,Sa0813;35.720278,-79.176389,other') indicates Saturdays from 8am to 1pm is at one location and all other times are at another location. Hours should be in 24 hours time using 2 digits, days of the week should be the first two characters of the day.If the day of the week does not appear then the time periods apply to all days (example '35.720278,-79.176389,0614,35.731944,-78.852778,1424') gives two time periods for all days. If hours do not appear then the time period applies to all hours of the day (example '35.720278,-79.176389,Sa,35.731944,-78.852778,Su')."
    type: string

